# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
use_frameworks!

target 'Assignment8' do
  pod 'SnapKit'
  pod 'Down'
  pod 'Kingfisher'
  pod 'RxCocoa'
  pod 'RxDataSources'
end
